import { expect, test } from 'bun:test';
import { bootstrapHolding, bootstrapHoldings, importBootstrapHoldings } from '../src/bootstrap.js';

const holding={symbol:'aapl',currency:'USD',quantity:'2',unitPrice:'100.25',date:'2024-01-01T00:00:00.000Z',isin:'US0378331005',market:'NASDAQ'};
test('creates an explicit idempotent opening BUY',()=>{const result=bootstrapHolding(holding,'ppi-account');expect(result).toMatchObject({type:'BUY',symbol:'AAPL',quantity:'2',unitPrice:'100.25',isin:'US0378331005',market:'NASDAQ'});expect(result.id).toMatch(/^ppi:ppi-account:[a-f0-9]{64}$/);expect(result.id).toBe(bootstrapHolding(holding,'ppi-account').id);});
test('rejects invalid bootstrap data',()=>{expect(()=>bootstrapHolding({...holding,date:'invalid'},'a')).toThrow('valid date');expect(()=>bootstrapHolding({...holding,quantity:'-1'},'a')).toThrow('non-negative');});
test('normalizes bootstrap currency aliases and rejects unknown currencies',()=>{expect(bootstrapHolding({...holding,currency:'Dólar MEP'},'ppi').currency).toBe('USD');expect(()=>bootstrapHolding({...holding,currency:'XYZ money'},'ppi')).toThrow('supported currency');});
test('preserves an explicit bootstrap data source',()=>{expect(bootstrapHoldings([{...holding,dataSource:'MANUAL'}],'ppi','ghost')[0].dataSource).toBe('MANUAL');});
test('maps an explicit bootstrap batch to Ghostfolio activities',()=>{const result=bootstrapHoldings([holding], 'ppi-account','ghost-account');expect(result).toHaveLength(1);expect(result[0]).toMatchObject({accountId:'ghost-account',type:'BUY',symbol:'AAPL',quantity:2,unitPrice:100.25,dataSource:'YAHOO'});});
test('makes bootstrap idempotent within a target account and honors dry-run',async()=>{let writes=0;let dryRun=false;let existing:{accountId:string;comment?:string}[]=[];const ghost={getActivities:async()=>existing,importActivities:async(activities:{accountId:string;comment?:string}[],options?:{dryRun?:boolean})=>{writes++;dryRun=options?.dryRun===true;if(!dryRun)existing=[...existing,...activities];return {dryRun,imported:activities.length,activities:[]};}};const dry=await importBootstrapHoldings([holding],'ppi',ghost,'target',{dryRun:true});expect(dry).toEqual({prepared:1,duplicates:0,imported:1});expect(dryRun).toBe(true);expect(existing).toHaveLength(0);const first=await importBootstrapHoldings([holding,holding],'ppi',ghost,'target',{dryRun:false});expect(first).toEqual({prepared:2,duplicates:1,imported:1});const second=await importBootstrapHoldings([holding],'ppi',ghost,'target',{dryRun:false});expect(second).toEqual({prepared:1,duplicates:1,imported:0});expect(writes).toBe(2);});
test('resumes a partially persisted bootstrap without duplicating the target account',async()=>{const existing:{accountId:string;comment?:string}[]=[];let calls=0;const ghost={getActivities:async()=>existing,importActivities:async(activities:{accountId:string;comment?:string}[])=>{calls++;if(calls===1){existing.push(activities[0]);throw new Error('connection failed');}existing.push(...activities);return {dryRun:false,imported:activities.length,activities:[]};}};await expect(importBootstrapHoldings([holding,{...holding,symbol:'MSFT'}],'ppi',ghost,'target',{dryRun:false})).rejects.toThrow('connection failed');const resumed=await importBootstrapHoldings([holding,{...holding,symbol:'MSFT'}],'ppi',ghost,'target',{dryRun:false});expect(resumed).toEqual({prepared:2,duplicates:1,imported:1});expect(existing).toHaveLength(2);});
