import { expect, test } from 'bun:test';
import { loadConfig, parseAccountMap, parseBootstrapCutoffDate, parsePpiAccountIds, parseSyncRange } from '../src/config.js';

const env = { PPI_API_URL:'https://ppi.example', PPI_AUTHORIZED_CLIENT:'authorized', PPI_CLIENT_KEY:'client', PPI_PUBLIC_KEY:'public', PPI_PRIVATE_KEY:'private', PPI_ACCOUNT_ID:'ppi', GHOSTFOLIO_URL:'https://ghostfolio.example', GHOSTFOLIO_ACCESS_TOKEN:'token', GHOSTFOLIO_ACCOUNT_ID:'ghost', SYNC_FROM_DATE:'2024-01-01' };
test('validates and maps configuration', () => expect(loadConfig({...env,SYNC_TO_DATE:'2024-01-31'})).toMatchObject({ dryRun:false, syncFromDate:new Date('2024-01-01T00:00:00.000Z'), syncToDate:new Date('2024-01-31T23:59:59.999Z'), ppi:{orderEnrichment:false},ghostfolio:{batchSize:100} }));
test('validates Ghostfolio batch size as a bounded positive integer',()=>{expect(loadConfig({...env,GHOSTFOLIO_BATCH_SIZE:'25'}).ghostfolio.batchSize).toBe(25);for(const value of ['0','-1','1.5','1e2',' 10','501','not-a-number'])expect(()=>loadConfig({...env,GHOSTFOLIO_BATCH_SIZE:value})).toThrow();});
test('rejects an inverted controlled date range', () => expect(() => loadConfig({...env,SYNC_TO_DATE:'2023-12-31'})).toThrow());
test('parses diagnostic controlled date ranges without Ghostfolio configuration',()=>{expect(parseSyncRange('2024-01-01','2024-01-31')).toEqual({from:new Date('2024-01-01T00:00:00.000Z'),to:new Date('2024-01-31T23:59:59.999Z')});expect(()=>parseSyncRange('2024-02-01','2024-01-31')).toThrow('must not be before');});
test('applies the bootstrap cutoff to normal history before any PPI request',()=>{const config=loadConfig({...env,SYNC_FROM_DATE:'2024-01-01',BOOTSTRAP_CUTOFF_DATE:'2024-01-15'});expect(config.syncFromDate).toEqual(new Date('2024-01-15T00:00:00.000Z'));expect(parseBootstrapCutoffDate('2024-01-15')).toEqual(new Date('2024-01-15T00:00:00.000Z'));expect(()=>loadConfig({...env,SYNC_TO_DATE:'2024-01-14',BOOTSTRAP_CUTOFF_DATE:'2024-01-15'})).toThrow('BOOTSTRAP_CUTOFF_DATE');});
test('parses opt-in manual cash assets',()=>expect(loadConfig({...env,PPI_CASH_ASSETS:'{"ARS":"GF_PPI_CASH_ARS","USD_MEP":"GF_PPI_CASH_USD_MEP"}'}).cashAssets).toEqual({ARS:'GF_PPI_CASH_ARS',USD_MEP:'GF_PPI_CASH_USD_MEP'}));
test('rejects an invalid manual cash asset map',()=>{expect(()=>loadConfig({...env,PPI_CASH_ASSETS:'{"USD":"PPI_CASH_USD"}'})).toThrow();expect(()=>loadConfig({...env,PPI_CASH_ASSETS:'{"ARS":"PPI_CASH_ARS"}'})).toThrow();});
test('enables read-only PPI order enrichment only when explicitly requested',()=>expect(loadConfig({...env,PPI_ORDER_ENRICHMENT:'true'}).ppi.orderEnrichment).toBe(true));
test('rejects invalid configuration', () => expect(() => loadConfig({...env, PPI_API_URL:'not-url'})).toThrow());
test('validates symbol overrides from environment JSON',()=>{const config=loadConfig({...env,PPI_SYMBOL_OVERRIDES:'[{"symbol":"AAPLD","mappedSymbol":"AAPL","market":"BYMA"}]'});expect(config.symbolOverrides[0]).toMatchObject({symbol:'AAPLD',mappedSymbol:'AAPL',market:'BYMA'});expect(()=>loadConfig({...env,PPI_SYMBOL_OVERRIDES:'[{"symbol":"AAPL"}]'})).toThrow();});
test('parses multiple PPI account ids without duplicates',()=>{expect(parsePpiAccountIds('a, b, a','fallback')).toEqual(['a','b']);expect(parsePpiAccountIds(undefined,'fallback')).toEqual(['fallback']);expect(()=>parsePpiAccountIds(' , ','fallback')).toThrow();});
test('parses an explicit PPI to Ghostfolio account map',()=>{expect(parseAccountMap('{"ppi-a":"ghost-a"," ppi-b ":" ghost-b "}')).toEqual({'ppi-a':'ghost-a','ppi-b':'ghost-b'});expect(()=>parseAccountMap('[]')).toThrow();expect(()=>parseAccountMap('{"ppi-a":""}')).toThrow();});
test('validates and maps log level',()=>{expect(loadConfig({...env,LOG_LEVEL:'debug'}).logLevel).toBe('debug');expect(()=>loadConfig({...env,LOG_LEVEL:'verbose'})).toThrow();});
