import { expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import { GhostfolioHttpClient } from '../src/ghostfolio/client.js';
import type { SyncConfig } from '../src/config.js';
const ghostfolioDividendFeeResponse=JSON.parse(readFileSync(new URL('./fixtures/ghostfolio-dividend-fee-response.json',import.meta.url),'utf8')) as unknown;
const config={url:'https://ghostfolio.example',accessToken:'secret',accountId:'account'} satisfies SyncConfig['ghostfolio'];
const activity={accountId:'account',type:'BUY',date:'2024-01-01T00:00:00.000Z',symbol:'AAPL',quantity:1,unitPrice:10,currency:'USD'};
test('imports with Ghostfolio dry-run query',async()=>{let request:Request|undefined;const client=new GhostfolioHttpClient(config,async(input,init)=>{request=new Request(input,init);return new Response(JSON.stringify({activities:[]}),{status:200});});const result=await client.importActivities([activity],{dryRun:true});expect(request?.url).toContain('/api/v1/import?dryRun=true');expect(request?.method).toBe('POST');expect(result.dryRun).toBe(true);});
test('reads activities',async()=>{const client=new GhostfolioHttpClient(config,async()=>new Response(JSON.stringify([{id:'1',type:'BUY'}]),{status:200}));expect(await client.getActivities()).toHaveLength(1);});
test('accepts the observed Ghostfolio dividend and fee response without symbols',async()=>{const client=new GhostfolioHttpClient(config,async()=>new Response(JSON.stringify(ghostfolioDividendFeeResponse),{status:200}));const activities=await client.getActivities();expect(activities).toHaveLength(2);expect(activities).toMatchObject([{type:'DIVIDEND',currency:'USD',unitPrice:1.23,comment:'ppi-sync:anonymized-dividend-fingerprint'},{type:'FEE',currency:'USD',unitPrice:0.45,comment:'ppi-sync:anonymized-fee-fingerprint'}]);expect(activities.every(activity=>!('symbol' in activity))).toBe(true);});
test('exchanges security token for authToken',async()=>{const calls:Request[]=[];const client=new GhostfolioHttpClient({...config,securityToken:'security'},async(input,init)=>{calls.push(new Request(input,init));return new Response(calls.length===1?JSON.stringify({authToken:'jwt'}):JSON.stringify([]),{status:200});});await client.getActivities();expect(calls[0].url).toContain('/api/v1/auth/anonymous');expect(calls[1].headers.get('authorization')).toBe('Bearer jwt');});
test('retries transient Ghostfolio import errors',async()=>{let calls=0;const client=new GhostfolioHttpClient(config,async()=>{calls++;return calls<3?new Response('busy',{status:503}):new Response(JSON.stringify({activities:[]}),{status:200});});const result=await client.importActivities([activity]);expect(calls).toBe(3);expect(result.imported).toBe(1);});
test('splits large Ghostfolio imports into batches',async()=>{let calls=0;const sizes:number[]=[];const client=new GhostfolioHttpClient(config,async(_input,init)=>{calls++;const body=JSON.parse(String(init?.body)) as {activities:unknown[]};sizes.push(body.activities.length);return new Response(JSON.stringify({activities:[]}),{status:200});});await client.importActivities(Array.from({length:101},()=>activity));expect(calls).toBe(2);expect(sizes).toEqual([100,1]);});
test('reports the failing batch range',async()=>{const client=new GhostfolioHttpClient(config,async()=>new Response('{"message":"invalid"}',{status:400}));expect(client.importActivities(Array.from({length:101},()=>activity))).rejects.toThrow('batch 1 (activities 1-100)');});
test('redacts secret-looking HTTP error details',async()=>{const client=new GhostfolioHttpClient(config,async()=>new Response('{"authorization":"Bearer leaked","accessToken":"secret"}',{status:400}));const error=client.importActivities([activity]);expect(error).rejects.toThrow('[REDACTED]');expect(error).rejects.not.toThrow('leaked');});
test('validates activity structure while allowing Ghostfolio extra fields',async()=>{const client=new GhostfolioHttpClient(config,async()=>new Response(JSON.stringify([{id:'1',type:'BUY',customField:'kept'}]),{status:200}));const result=await client.getActivities();expect(result[0]).toMatchObject({id:'1',customField:'kept'});});
test('sanitizes Ghostfolio authentication and activity errors',async()=>{const authClient=new GhostfolioHttpClient({...config,securityToken:'security'},async()=>new Response('{"accessToken":"auth-secret"}',{status:401}));expect(authClient.getActivities()).rejects.toThrow('[REDACTED]');const activityClient=new GhostfolioHttpClient(config,async()=>new Response('{"securityToken":"activity-secret"}',{status:503}));expect(activityClient.getActivities()).rejects.toThrow('[REDACTED]');});

