import { expect, test } from 'bun:test';
import { syncMepBalanceProjection } from '../src/mep-balance-projection.js';
import type { GhostfolioActivity, GhostfolioImportActivity } from '../src/ghostfolio/types.js';

test('projects configured MEP balances per source and remains idempotent',async()=>{let existing:GhostfolioActivity[]=[];const imported:GhostfolioImportActivity[][]=[];const ghost={getActivities:async()=>existing,importActivities:async(activities:GhostfolioImportActivity[],options?:{dryRun?:boolean})=>{const result=activities.map((activity,index)=>({...activity,id:`activity-${index}`})) as GhostfolioActivity[];imported.push(activities);if(!options?.dryRun)existing=[...existing,...result];return {dryRun:options?.dryRun===true,imported:activities.length,activities:result,validationFailures:[]};},updateActivity:async()=>{throw new Error('unchanged projections must not update activities');}};const projection={accountIds:['first','second'],values:[2472.29,178.97]};const first=await syncMepBalanceProjection(ghost,projection,{dryRun:false,date:new Date('2026-09-12T00:00:00.000Z')});expect(first).toEqual({prepared:2,imported:2,updated:0,duplicates:0,marketData:0});expect(imported[0]).toMatchObject([{accountId:'first',type:'BUY',symbol:'GF_PPI_MEP_SNAPSHOT_1',quantity:2472.29,dataSource:'MANUAL'},{accountId:'second',type:'BUY',symbol:'GF_PPI_MEP_SNAPSHOT_2',quantity:178.97,dataSource:'MANUAL'}]);expect(await syncMepBalanceProjection(ghost,projection,{dryRun:false})).toEqual({prepared:2,imported:0,updated:0,duplicates:2,marketData:0});});

test('updates the one existing projection instead of adding a compensating activity',async()=>{const existing:GhostfolioActivity[]=[{id:'existing',accountId:'first',type:'BUY',date:'2026-09-12T00:00:00.000Z',quantity:100,comment:'ppi-mep-snapshot:1:100.00',SymbolProfile:{symbol:'GF_PPI_MEP_SNAPSHOT_1'}}];const updates:(GhostfolioImportActivity&{id:string})[]=[];const ghost={getActivities:async()=>existing,importActivities:async()=>{throw new Error('an existing projection must not create another activity');},updateActivity:async(activity:GhostfolioImportActivity&{id:string})=>{updates.push(activity);}};const result=await syncMepBalanceProjection(ghost,{accountIds:['first'],values:[90.25]},{dryRun:false});expect(result).toEqual({prepared:1,imported:0,updated:1,duplicates:0,marketData:0});expect(updates).toEqual([expect.objectContaining({id:'existing',type:'BUY',quantity:90.25,symbol:'GF_PPI_MEP_SNAPSHOT_1'})]);});

test('recognizes the original seeded snapshot comment',async()=>{const existing:GhostfolioActivity[]=[{id:'seed',accountId:'first',type:'BUY',quantity:2472.29,comment:'ppi-balance-snapshot:source-1:2026-09-12'}];const ghost={getActivities:async()=>existing,importActivities:async()=>{throw new Error('the seeded snapshot must not be duplicated');},updateActivity:async()=>{throw new Error('an equal seeded snapshot must not be updated');}};expect(await syncMepBalanceProjection(ghost,{accountIds:['first'],values:[2472.29]},{dryRun:false})).toEqual({prepared:1,imported:0,updated:0,duplicates:1,marketData:0});});

test('turns explicit PPI period returns into manual market data before rewriting the snapshot',async()=>{const existing:GhostfolioActivity[]=[{id:'existing',accountId:'first',type:'BUY',date:'2026-09-12T00:00:00.000Z',quantity:100,unitPrice:1,comment:'ppi-mep-snapshot:1:100.00',SymbolProfile:{symbol:'GF_PPI_MEP_SNAPSHOT_1'}}];const calls:string[]=[];const profiles:unknown[]=[];const ghost={getActivities:async()=>existing,importActivities:async()=>{throw new Error('existing activity should be updated');},upsertManualAssetProfiles:async(value:unknown[])=>{calls.push('market-data');profiles.push(...value);},updateActivity:async(activity:GhostfolioImportActivity&{id:string})=>{calls.push('activity');expect(activity).toMatchObject({date:'2026-08-13T00:00:00.000Z',unitPrice:1/1.0337});}};const result=await syncMepBalanceProjection(ghost,{accountIds:['first'],values:[100],performancePercentages:[3.37],asOfDate:'2026-09-12'},{dryRun:false});expect(result).toEqual({prepared:1,imported:0,updated:1,duplicates:0,marketData:1});expect(calls).toEqual(['market-data','activity']);expect(profiles).toMatchObject([{marketData:[{date:'2026-08-13T00:00:00.000Z',marketPrice:1/1.0337},{date:'2026-09-12T00:00:00.000Z',marketPrice:1}]}]);});
