import { expect, test } from 'bun:test';
import { PpiHttpClient } from '../src/ppi/client.js';
import type { SyncConfig } from '../src/config.js';
const config={apiUrl:'https://ppi.example',authorizedClient:'authorized',clientKey:'client',publicKey:'public',privateKey:'private',accountId:'account',accountIds:['account']} satisfies SyncConfig['ppi'];
const token=[{accessToken:'access',refreshToken:'refresh',tokenType:'Bearer',expires:3600}];
const movements=[{agreementDate:'2024-01-01T12:00:00Z',currency:'ARS',amount:100,price:10,description:'Compra de acciones',ticker:'GGAL',quantity:10,balance:0}];
test('authenticates and reads movements without trading methods',async()=>{const calls:Request[]=[];const fetcher=async(input:RequestInfo|URL,init?:RequestInit)=>{calls.push(new Request(input,init));return new Response(calls.length===1?JSON.stringify(token):JSON.stringify(movements),{status:200});};const client=new PpiHttpClient(config,fetcher);const result=await client.getTransactions({accountId:'acc',from:new Date('2024-01-01T00:00:00Z')});expect(result).toHaveLength(1);expect(calls[0].method).toBe('POST');expect(calls[1].url).toContain('/api/1.0/Account/Movements');expect(calls[1].url).toContain('accountNumber=acc');expect(calls[1].url).toContain('dateTo=');});
test('protects PPI authentication with timeout and redacted errors',async()=>{let signal:AbortSignal|undefined;const client=new PpiHttpClient(config,async(_input,init)=>{signal=init?.signal as AbortSignal;return new Response('{"privateKey":"secret"}',{status:400});});expect(client.authenticate()).rejects.toThrow('[REDACTED]');expect(signal).toBeDefined();});
test('reads grouped availability from the PPI account response',async()=>{const client=new PpiHttpClient(config,async(_input,init)=>{const request=new Request(_input,init);return request.url.includes('BalancesAndPositions')?new Response(JSON.stringify({groupedAvailability:[{currency:'USD',availability:[{name:'AAPL',simbol:'AAPL',amount:2,settlement:'T+2'}]}],groupedInstruments:[]} ),{status:200}):new Response(JSON.stringify(token),{status:200});});const result=await client.getAccount('acc');expect(result).toEqual([{currency:'USD',availability:[{name:'AAPL',simbol:'AAPL',amount:2,settlement:'T+2'}]}]);});
