import type { SyncConfig } from '../config.js';
import { PpiAuth } from './auth.js';
import { balancesSchema, instrumentsSchema, transactionsSchema } from './schemas.js';
import type { PpiAccountBalance, PpiClient, PpiInstrument, PpiTransaction } from './types.js';
type Fetcher=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;
export class PpiHttpClient implements PpiClient { private readonly auth:PpiAuth; private readonly instrumentCache=new Map<string,PpiInstrument[]>(); constructor(private readonly config:SyncConfig['ppi'],private readonly fetcher:Fetcher=fetch){this.auth=new PpiAuth(config,fetcher);} async authenticate(){await this.auth.authenticate();} private headers(){return {AuthorizedClient:this.config.authorizedClient,ClientKey:this.config.clientKey,Authorization:`Bearer ${this.auth.accessToken}`};}
 async getTransactions(options:{accountId:string;from?:Date;to?:Date}):Promise<PpiTransaction[]>{if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/Account/Movements',this.config.apiUrl);url.searchParams.set('accountNumber',options.accountId);if(options.from)url.searchParams.set('dateFrom',options.from.toISOString());if(options.to)url.searchParams.set('dateTo',options.to.toISOString());else if(options.from)url.searchParams.set('dateTo',new Date().toISOString());const res=await this.fetcher(url,{headers:this.headers(),signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error(`PPI transactions HTTP error ${res.status}`);return transactionsSchema.parse(await res.json());}
 async searchInstrument(ticker:string):Promise<PpiInstrument[]>{const key=ticker.trim().toUpperCase();const cached=this.instrumentCache.get(key);if(cached)return cached;if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/MarketData/SearchInstrument',this.config.apiUrl);url.searchParams.set('Ticker',key);const res=await this.fetcher(url,{headers:this.headers(),signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error(`PPI instrument search HTTP error ${res.status}`);const instruments=instrumentsSchema.parse(await res.json());this.instrumentCache.set(key,instruments);return instruments;}
 async getAccount(accountId:string):Promise<PpiAccountBalance[]>{if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/Account/BalancesAndPositions',this.config.apiUrl);url.searchParams.set('accountNumber',accountId);const res=await this.fetcher(url,{headers:this.headers(),signal:AbortSignal.timeout(15000)});if(!res.ok)throw new Error(`PPI account HTTP error ${res.status}`);const body:unknown=await res.json();if(Array.isArray(body))return balancesSchema.parse(body);if(!body||typeof body!=='object')throw new Error('PPI account response is not an object or array');const value=body as {groupedAvailability?:unknown};if(!Array.isArray(value.groupedAvailability))throw new Error('PPI account response has no groupedAvailability array');return balancesSchema.parse(value.groupedAvailability);}
}
