import type { SyncConfig } from '../config.js';
import { parsePpiJson } from './decimals.js';
import { PpiAuth } from './auth.js';
import { balancesSchema, instrumentsSchema, orderSchema, ordersSchema, positionsResponseSchema, transactionsSchema } from './schemas.js';
import type { PpiAccountBalance, PpiClient, PpiInstrument, PpiOrder, PpiPosition, PpiTransaction } from './types.js';
type Fetcher=(input:RequestInfo|URL,init?:RequestInit)=>Promise<Response>;
export class PpiHttpClient implements PpiClient { private readonly auth:PpiAuth; private readonly instrumentCache=new Map<string,PpiInstrument[]>(); constructor(private readonly config:SyncConfig['ppi'],private readonly fetcher:Fetcher=fetch){this.auth=new PpiAuth(config,fetcher);} async authenticate(){await this.auth.authenticate();} private headers(){return {AuthorizedClient:this.config.authorizedClient,ClientKey:this.config.clientKey,Authorization:`Bearer ${this.auth.accessToken}`};}
 private async get(url:URL,label:string):Promise<Response>{for(let attempt=0;attempt<3;attempt++){const res=await this.fetcher(url,{headers:this.headers(),signal:AbortSignal.timeout(15000)});if(res.ok)return res;const transient=res.status===408||res.status>=500;if(!transient||attempt===2)throw new Error(`PPI ${label} HTTP error ${res.status}`);await new Promise(resolve=>setTimeout(resolve,100*(attempt+1)));}throw new Error('PPI read retry loop exited unexpectedly');}
 async getTransactions(options:{accountId:string;from?:Date;to?:Date}):Promise<PpiTransaction[]>{if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/Account/Movements',this.config.apiUrl);url.searchParams.set('accountNumber',options.accountId);if(options.from)url.searchParams.set('dateFrom',options.from.toISOString());if(options.to)url.searchParams.set('dateTo',options.to.toISOString());else if(options.from)url.searchParams.set('dateTo',new Date().toISOString());return transactionsSchema.parse(parsePpiJson(await (await this.get(url,'transactions')).text()));}
 async getOrders(options:{accountId:string;from?:Date;to?:Date}):Promise<PpiOrder[]>{if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/Order/Orders',this.config.apiUrl);url.searchParams.set('accountNumber',options.accountId);if(options.from)url.searchParams.set('dateFrom',options.from.toISOString());if(options.to)url.searchParams.set('dateTo',options.to.toISOString());else if(options.from)url.searchParams.set('dateTo',new Date().toISOString());return ordersSchema.parse(parsePpiJson(await (await this.get(url,'orders')).text())).map(order=>({...order,externalId:order.externalID??undefined}));}
 async getOrderDetail(options:{accountId:string;orderId:number;externalId?:string}):Promise<PpiOrder>{if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/Order/Detail',this.config.apiUrl);url.searchParams.set('accountNumber',options.accountId);url.searchParams.set('orderID',String(options.orderId));if(options.externalId)url.searchParams.set('externalID',options.externalId);const order=orderSchema.parse(parsePpiJson(await (await this.get(url,'order detail')).text()));return {...order,externalId:order.externalID??undefined};}
 async searchInstrument(ticker:string):Promise<PpiInstrument[]>{const key=ticker.trim().toUpperCase();const cached=this.instrumentCache.get(key);if(cached)return cached;if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/MarketData/SearchInstrument',this.config.apiUrl);url.searchParams.set('Ticker',key);const instruments=instrumentsSchema.parse(await (await this.get(url,'instrument search')).json());this.instrumentCache.set(key,instruments);return instruments;}
 private async getAccountBody(accountId:string):Promise<unknown>{if(!this.auth.accessToken)await this.authenticate();const url=new URL('/api/1.0/Account/BalancesAndPositions',this.config.apiUrl);url.searchParams.set('accountNumber',accountId);return (await this.get(url,'account')).json();}
 async getAccount(accountId:string):Promise<PpiAccountBalance[]>{const body=await this.getAccountBody(accountId);if(Array.isArray(body))return balancesSchema.parse(body);if(!body||typeof body!=='object')throw new Error('PPI account response is not an object or array');const value=body as {groupedAvailability?:unknown};if(!Array.isArray(value.groupedAvailability))throw new Error('PPI account response has no groupedAvailability array');return balancesSchema.parse(value.groupedAvailability);}
 async getPositions(accountId:string):Promise<PpiPosition[]>{const body=await this.getAccountBody(accountId);if(!body||typeof body!=='object'||Array.isArray(body))throw new Error('PPI account response has no groupedInstruments positions');return positionsResponseSchema.parse(body).groupedInstruments.flatMap(group=>group.instruments);}
}
