import { createHash } from 'node:crypto';
import type { NormalizedTransaction } from '../types.js';
export const FINGERPRINT_VERSION='v2';
type IdentityOptions={externalId?:string;sourceBalance?:string};
const digest=(canonical:string[]):string=>createHash('sha256').update(canonical.join('|'),'utf8').digest('hex');
const identityOptions=(transaction:NormalizedTransaction):IdentityOptions[]=>{const values:IdentityOptions[]=[];for(const externalId of transaction.externalId?[transaction.externalId,undefined]:[undefined])for(const sourceBalance of transaction.sourceBalance?[transaction.sourceBalance,undefined]:[undefined])values.push({externalId,sourceBalance});return values;};
const canonicalV2=(transaction:NormalizedTransaction,options:IdentityOptions):string[]=>['ppi',FINGERPRINT_VERSION,transaction.accountId,options.externalId??'',transaction.type,transaction.date.toISOString(),transaction.sourceSymbol??transaction.symbol??'',transaction.quantity??'',transaction.unitPrice??'',transaction.fee??'',transaction.currency,options.sourceBalance??''];
const canonicalLegacy=(transaction:NormalizedTransaction,options:IdentityOptions):string[]=>['ppi',transaction.accountId,options.externalId??'',transaction.type,transaction.date.toISOString(),transaction.symbol??'',transaction.quantity??'',transaction.unitPrice??'',transaction.fee??'',transaction.currency,options.sourceBalance??''];
const canonicalPreV03=(transaction:NormalizedTransaction,options:IdentityOptions):string[]=>['ppi',transaction.accountId,options.externalId??'',transaction.type,transaction.date.toISOString(),transaction.symbol??'',transaction.quantity??'',transaction.unitPrice??'',transaction.fee??'',transaction.currency];
export function transactionFingerprint(transaction:NormalizedTransaction):string { return digest(canonicalV2(transaction,{externalId:transaction.externalId,sourceBalance:transaction.sourceBalance})); }
export function transactionId(transaction:NormalizedTransaction):string { return `ppi:${FINGERPRINT_VERSION}:${transaction.accountId}:${transactionFingerprint(transaction)}`; }
export function compatibleTransactionIds(transaction:NormalizedTransaction):string[]{const options=identityOptions(transaction);const versioned=options.map(value=>`ppi:${FINGERPRINT_VERSION}:${transaction.accountId}:${digest(canonicalV2(transaction,value))}`);const legacy=options.map(value=>`ppi:${transaction.accountId}:${digest(canonicalLegacy(transaction,value))}`);const preV03=options.map(value=>`ppi:${transaction.accountId}:${digest(canonicalPreV03(transaction,value))}`);return [...new Set([...versioned,...legacy,...preV03])];}
export function sourceMovementFingerprint(value:{agreementDate:string;settlementDate?:string;currency:string;amount:string|number;price:string|number;description:string;ticker?:string;quantity:string|number;balance:string|number}):string{return createHash('sha256').update([value.agreementDate,value.settlementDate??'',value.currency,value.amount,value.price,value.description,value.ticker??'',value.quantity,value.balance].join('|'),'utf8').digest('hex');}
