import { z } from 'zod';
import { parseSymbolOverrides } from './mapping/symbol-overrides.js';
import type { SymbolOverride } from './mapping/symbol-overrides.js';
import { cashAssetBuckets, parseCashAssetMap } from './mapping/cash-assets.js';
import type { CashAssetBucket, CashAssetMap } from './mapping/cash-assets.js';
const ppiSchema=z.object({PPI_API_URL:z.string().url(),PPI_AUTHORIZED_CLIENT:z.string().min(1),PPI_CLIENT_KEY:z.string().min(1),PPI_PUBLIC_KEY:z.string().min(1),PPI_PRIVATE_KEY:z.string().min(1),PPI_ACCOUNT_ID:z.string().min(1),PPI_ORDER_ENRICHMENT:z.enum(['true','false']).default('false'),PPI_ORDER_FALLBACK:z.enum(['true','false']).default('false')});
const syncRangeSchema=z.object({SYNC_FROM_DATE:z.string().date().optional(),SYNC_TO_DATE:z.string().date().optional()});
const bootstrapCutoffSchema=z.object({BOOTSTRAP_CUTOFF_DATE:z.string().date().optional()});
export const GHOSTFOLIO_BATCH_SIZE_DEFAULT=100;
export const GHOSTFOLIO_BATCH_SIZE_MAX=500;
const batchSizeSchema=z.preprocess(value=>{if(value===undefined)return GHOSTFOLIO_BATCH_SIZE_DEFAULT;if(typeof value==='string'&&/^[1-9]\d*$/.test(value))return Number(value);return value;},z.number().int().min(1).max(GHOSTFOLIO_BATCH_SIZE_MAX));
const optionalNonEmptyString=z.preprocess(value=>value===''?undefined:value,z.string().min(1).optional());
const ghostfolioFields={GHOSTFOLIO_URL:z.string().url(),GHOSTFOLIO_ACCESS_TOKEN:z.string().min(1).optional(),GHOSTFOLIO_SECURITY_TOKEN:z.string().min(1).optional(),GHOSTFOLIO_ACCOUNT_ID:optionalNonEmptyString,GHOSTFOLIO_ACCOUNT_ID_ARS:optionalNonEmptyString,GHOSTFOLIO_ACCOUNT_ID_USD:optionalNonEmptyString,GHOSTFOLIO_BATCH_SIZE:batchSizeSchema};
const validateGhostfolioTargets=(value:{GHOSTFOLIO_ACCOUNT_ID?:string;GHOSTFOLIO_ACCOUNT_ID_ARS?:string;GHOSTFOLIO_ACCOUNT_ID_USD?:string},context:z.RefinementCtx):void=>{const splitConfigured=Boolean(value.GHOSTFOLIO_ACCOUNT_ID_ARS||value.GHOSTFOLIO_ACCOUNT_ID_USD);if(!value.GHOSTFOLIO_ACCOUNT_ID&&!splitConfigured)context.addIssue({code:z.ZodIssueCode.custom,message:'GHOSTFOLIO_ACCOUNT_ID or both GHOSTFOLIO_ACCOUNT_ID_ARS and GHOSTFOLIO_ACCOUNT_ID_USD is required'});if(splitConfigured&&(!value.GHOSTFOLIO_ACCOUNT_ID_ARS||!value.GHOSTFOLIO_ACCOUNT_ID_USD))context.addIssue({code:z.ZodIssueCode.custom,message:'GHOSTFOLIO_ACCOUNT_ID_ARS and GHOSTFOLIO_ACCOUNT_ID_USD must be configured together'});if(value.GHOSTFOLIO_ACCOUNT_ID&&splitConfigured)context.addIssue({code:z.ZodIssueCode.custom,message:'Configure either GHOSTFOLIO_ACCOUNT_ID or the ARS/USD split target variables, not both'});};
const schema=ppiSchema.extend({...ghostfolioFields,DRY_RUN:z.enum(['true','false']).default('false'),LOG_LEVEL:z.enum(['debug','info','warn','error']).default('info'),SYNC_FROM_DATE:z.string().date().optional(),SYNC_TO_DATE:z.string().date().optional(),BOOTSTRAP_CUTOFF_DATE:z.string().date().optional(),PPI_CASH_ACTIVITY_IMPORT:z.enum(['true','false']).default('false'),PPI_CASH_ENABLED_BUCKETS:z.string().optional()}).superRefine((value,context)=>{if(!value.GHOSTFOLIO_ACCESS_TOKEN&&!value.GHOSTFOLIO_SECURITY_TOKEN)context.addIssue({code:z.ZodIssueCode.custom,message:'GHOSTFOLIO_ACCESS_TOKEN or GHOSTFOLIO_SECURITY_TOKEN is required'});validateGhostfolioTargets(value,context);});
const ghostfolioSchema=z.object(ghostfolioFields).superRefine((value,context)=>{if(!value.GHOSTFOLIO_ACCESS_TOKEN&&!value.GHOSTFOLIO_SECURITY_TOKEN)context.addIssue({code:z.ZodIssueCode.custom,message:'GHOSTFOLIO_ACCESS_TOKEN or GHOSTFOLIO_SECURITY_TOKEN is required'});validateGhostfolioTargets(value,context);});
export interface PpiConfig {apiUrl:string;authorizedClient:string;clientKey:string;publicKey:string;privateKey:string;accountId:string;accountIds:string[];orderEnrichment:boolean;orderFallback?:boolean}
export function parsePpiAccountIds(value:string|undefined,defaultAccount:string):string[]{if(!value)return [defaultAccount];const ids=value.split(',').map(id=>id.trim()).filter(Boolean);if(ids.length===0)throw new Error('PPI_ACCOUNT_IDS must contain at least one account');if(new Set(ids).size!==ids.length)throw new Error('PPI_ACCOUNT_IDS must not contain duplicate account IDs');return ids;}
export interface GhostfolioConfig {url:string;accessToken:string;securityToken?:string;accountId?:string;accountIdsByCurrency?:{ARS:string;USD:string};batchSize:number}
export interface SyncConfig { ppi:PpiConfig; ghostfolio:GhostfolioConfig; dryRun:boolean; logLevel:'debug'|'info'|'warn'|'error'; syncFromDate?:Date; syncToDate?:Date; bootstrapCutoffDate?:Date; symbolOverrides:ReturnType<typeof parseSymbolOverrides>; cashAssets:CashAssetMap; cashActivityImport:boolean; }
export function loadPpiConfig(env:NodeJS.ProcessEnv):PpiConfig { const v=ppiSchema.parse(env); return {apiUrl:v.PPI_API_URL,authorizedClient:v.PPI_AUTHORIZED_CLIENT,clientKey:v.PPI_CLIENT_KEY,publicKey:v.PPI_PUBLIC_KEY,privateKey:v.PPI_PRIVATE_KEY,accountId:v.PPI_ACCOUNT_ID,accountIds:parsePpiAccountIds(env.PPI_ACCOUNT_IDS,v.PPI_ACCOUNT_ID),orderEnrichment:v.PPI_ORDER_ENRICHMENT==='true',orderFallback:v.PPI_ORDER_FALLBACK==='true'}; }
function ghostfolioConfig(value:z.infer<typeof ghostfolioSchema>):GhostfolioConfig{return {url:value.GHOSTFOLIO_URL,accessToken:value.GHOSTFOLIO_ACCESS_TOKEN??'',securityToken:value.GHOSTFOLIO_SECURITY_TOKEN,accountId:value.GHOSTFOLIO_ACCOUNT_ID,accountIdsByCurrency:value.GHOSTFOLIO_ACCOUNT_ID_ARS&&value.GHOSTFOLIO_ACCOUNT_ID_USD?{ARS:value.GHOSTFOLIO_ACCOUNT_ID_ARS,USD:value.GHOSTFOLIO_ACCOUNT_ID_USD}:undefined,batchSize:value.GHOSTFOLIO_BATCH_SIZE};}
export function loadGhostfolioConfig(env:NodeJS.ProcessEnv):GhostfolioConfig { return ghostfolioConfig(ghostfolioSchema.parse(env)); }
export function requireSingleGhostfolioAccount(config:GhostfolioConfig,command:string):string{if(!config.accountId)throw new Error(`${command} requires legacy GHOSTFOLIO_ACCOUNT_ID; currency-split targets are supported by normal sync only`);return config.accountId;}
export function parseSyncRange(syncFromDate?:string,syncToDate?:string):{from?:Date;to?:Date}{const value=syncRangeSchema.parse({SYNC_FROM_DATE:syncFromDate,SYNC_TO_DATE:syncToDate});const from=value.SYNC_FROM_DATE?new Date(`${value.SYNC_FROM_DATE}T00:00:00.000Z`):undefined;const to=value.SYNC_TO_DATE?new Date(`${value.SYNC_TO_DATE}T23:59:59.999Z`):undefined;if(from&&to&&to<from)throw new Error('SYNC_TO_DATE must not be before SYNC_FROM_DATE');return {from,to};}
export function parseBootstrapCutoffDate(value?:string):Date|undefined{const parsed=bootstrapCutoffSchema.parse({BOOTSTRAP_CUTOFF_DATE:value}).BOOTSTRAP_CUTOFF_DATE;return parsed?new Date(`${parsed}T00:00:00.000Z`):undefined;}
export function parseCashEnabledBuckets(value?:string):CashAssetBucket[]{if(!value)return [];const buckets=value.split(',').map(bucket=>bucket.trim()).filter(Boolean);if(buckets.length===0||new Set(buckets).size!==buckets.length||buckets.some(bucket=>!cashAssetBuckets.includes(bucket as CashAssetBucket)))throw new Error('PPI_CASH_ENABLED_BUCKETS must be a unique comma-separated list of ARS, USD_GLOBAL, USD_MEP, USD_CCL');return buckets as CashAssetBucket[];}
export function loadConfig(env:NodeJS.ProcessEnv):SyncConfig { const v=schema.parse(env); const range=parseSyncRange(env.SYNC_FROM_DATE,env.SYNC_TO_DATE); const bootstrapCutoffDate=parseBootstrapCutoffDate(env.BOOTSTRAP_CUTOFF_DATE); const syncFromDate=bootstrapCutoffDate&&(!range.from||bootstrapCutoffDate>range.from)?bootstrapCutoffDate:range.from;if(syncFromDate&&range.to&&range.to<syncFromDate)throw new Error('SYNC_TO_DATE must not be before BOOTSTRAP_CUTOFF_DATE'); let symbolOverrides:SymbolOverride[]=[]; if(env.PPI_SYMBOL_OVERRIDES) symbolOverrides=parseSymbolOverrides(JSON.parse(env.PPI_SYMBOL_OVERRIDES)); const configuredCashAssets=env.PPI_CASH_ASSETS?parseCashAssetMap(JSON.parse(env.PPI_CASH_ASSETS)):{}; const enabledCashBuckets=parseCashEnabledBuckets(v.PPI_CASH_ENABLED_BUCKETS); if(v.PPI_CASH_ACTIVITY_IMPORT==='true'&&enabledCashBuckets.length===0)throw new Error('PPI_CASH_ENABLED_BUCKETS is required when PPI_CASH_ACTIVITY_IMPORT=true'); if(v.PPI_CASH_ACTIVITY_IMPORT==='true'&&enabledCashBuckets.some(bucket=>!configuredCashAssets[bucket]))throw new Error('Every enabled cash bucket requires a configured manual cash asset'); const cashAssets=v.PPI_CASH_ACTIVITY_IMPORT==='true'?Object.fromEntries(enabledCashBuckets.map(bucket=>[bucket,configuredCashAssets[bucket]!])) as CashAssetMap:configuredCashAssets; return {ppi:loadPpiConfig(env),ghostfolio:ghostfolioConfig(v),dryRun:v.DRY_RUN==='true',logLevel:v.LOG_LEVEL,syncFromDate,syncToDate:range.to,bootstrapCutoffDate,symbolOverrides,cashAssets,cashActivityImport:v.PPI_CASH_ACTIVITY_IMPORT==='true'}; }
