import { z } from 'zod';
import { parseSymbolOverrides } from './mapping/symbol-overrides.js';
import type { SymbolOverride } from './mapping/symbol-overrides.js';
import { parseCashAssetMap } from './mapping/cash-assets.js';
import type { CashAssetMap } from './mapping/cash-assets.js';
const ppiSchema=z.object({PPI_API_URL:z.string().url(),PPI_AUTHORIZED_CLIENT:z.string().min(1),PPI_CLIENT_KEY:z.string().min(1),PPI_PUBLIC_KEY:z.string().min(1),PPI_PRIVATE_KEY:z.string().min(1),PPI_ACCOUNT_ID:z.string().min(1),PPI_ORDER_ENRICHMENT:z.enum(['true','false']).default('false')});
const syncRangeSchema=z.object({SYNC_FROM_DATE:z.string().date().optional(),SYNC_TO_DATE:z.string().date().optional()});
const bootstrapCutoffSchema=z.object({BOOTSTRAP_CUTOFF_DATE:z.string().date().optional()});
export const GHOSTFOLIO_BATCH_SIZE_DEFAULT=100;
export const GHOSTFOLIO_BATCH_SIZE_MAX=500;
const batchSizeSchema=z.preprocess(value=>{if(value===undefined)return GHOSTFOLIO_BATCH_SIZE_DEFAULT;if(typeof value==='string'&&/^[1-9]\d*$/.test(value))return Number(value);return value;},z.number().int().min(1).max(GHOSTFOLIO_BATCH_SIZE_MAX));
const schema=ppiSchema.extend({GHOSTFOLIO_URL:z.string().url(),GHOSTFOLIO_ACCESS_TOKEN:z.string().min(1).optional(),GHOSTFOLIO_SECURITY_TOKEN:z.string().min(1).optional(),GHOSTFOLIO_ACCOUNT_ID:z.string().min(1),GHOSTFOLIO_BATCH_SIZE:batchSizeSchema,DRY_RUN:z.enum(['true','false']).default('false'),LOG_LEVEL:z.enum(['debug','info','warn','error']).default('info'),SYNC_FROM_DATE:z.string().date().optional(),SYNC_TO_DATE:z.string().date().optional(),BOOTSTRAP_CUTOFF_DATE:z.string().date().optional()}).refine(value=>Boolean(value.GHOSTFOLIO_ACCESS_TOKEN||value.GHOSTFOLIO_SECURITY_TOKEN),{message:'GHOSTFOLIO_ACCESS_TOKEN or GHOSTFOLIO_SECURITY_TOKEN is required'});
const ghostfolioSchema=z.object({GHOSTFOLIO_URL:z.string().url(),GHOSTFOLIO_ACCESS_TOKEN:z.string().min(1).optional(),GHOSTFOLIO_SECURITY_TOKEN:z.string().min(1).optional(),GHOSTFOLIO_ACCOUNT_ID:z.string().min(1),GHOSTFOLIO_BATCH_SIZE:batchSizeSchema}).refine(value=>Boolean(value.GHOSTFOLIO_ACCESS_TOKEN||value.GHOSTFOLIO_SECURITY_TOKEN),{message:'GHOSTFOLIO_ACCESS_TOKEN or GHOSTFOLIO_SECURITY_TOKEN is required'});
export interface PpiConfig {apiUrl:string;authorizedClient:string;clientKey:string;publicKey:string;privateKey:string;accountId:string;accountIds:string[];orderEnrichment:boolean}
export function parsePpiAccountIds(value:string|undefined,defaultAccount:string):string[]{if(!value)return [defaultAccount];const ids=value.split(',').map(id=>id.trim()).filter(Boolean);if(ids.length===0)throw new Error('PPI_ACCOUNT_IDS must contain at least one account');return [...new Set(ids)];}
export interface GhostfolioConfig {url:string;accessToken:string;securityToken?:string;accountId:string;batchSize:number}
export interface SyncConfig { ppi:PpiConfig; ghostfolio:GhostfolioConfig; dryRun:boolean; logLevel:'debug'|'info'|'warn'|'error'; syncFromDate?:Date; syncToDate?:Date; bootstrapCutoffDate?:Date; symbolOverrides:ReturnType<typeof parseSymbolOverrides>; cashAssets:CashAssetMap; }
export function loadPpiConfig(env:NodeJS.ProcessEnv):PpiConfig { const v=ppiSchema.parse(env); return {apiUrl:v.PPI_API_URL,authorizedClient:v.PPI_AUTHORIZED_CLIENT,clientKey:v.PPI_CLIENT_KEY,publicKey:v.PPI_PUBLIC_KEY,privateKey:v.PPI_PRIVATE_KEY,accountId:v.PPI_ACCOUNT_ID,accountIds:parsePpiAccountIds(env.PPI_ACCOUNT_IDS,v.PPI_ACCOUNT_ID),orderEnrichment:v.PPI_ORDER_ENRICHMENT==='true'}; }
export function loadGhostfolioConfig(env:NodeJS.ProcessEnv):GhostfolioConfig { const v=ghostfolioSchema.parse(env); return {url:v.GHOSTFOLIO_URL,accessToken:v.GHOSTFOLIO_ACCESS_TOKEN??'',securityToken:v.GHOSTFOLIO_SECURITY_TOKEN,accountId:v.GHOSTFOLIO_ACCOUNT_ID,batchSize:v.GHOSTFOLIO_BATCH_SIZE}; }
export function parseSyncRange(syncFromDate?:string,syncToDate?:string):{from?:Date;to?:Date}{const value=syncRangeSchema.parse({SYNC_FROM_DATE:syncFromDate,SYNC_TO_DATE:syncToDate});const from=value.SYNC_FROM_DATE?new Date(`${value.SYNC_FROM_DATE}T00:00:00.000Z`):undefined;const to=value.SYNC_TO_DATE?new Date(`${value.SYNC_TO_DATE}T23:59:59.999Z`):undefined;if(from&&to&&to<from)throw new Error('SYNC_TO_DATE must not be before SYNC_FROM_DATE');return {from,to};}
export function parseBootstrapCutoffDate(value?:string):Date|undefined{const parsed=bootstrapCutoffSchema.parse({BOOTSTRAP_CUTOFF_DATE:value}).BOOTSTRAP_CUTOFF_DATE;return parsed?new Date(`${parsed}T00:00:00.000Z`):undefined;}
export function loadConfig(env:NodeJS.ProcessEnv):SyncConfig { const v=schema.parse(env); const range=parseSyncRange(env.SYNC_FROM_DATE,env.SYNC_TO_DATE); const bootstrapCutoffDate=parseBootstrapCutoffDate(env.BOOTSTRAP_CUTOFF_DATE); const syncFromDate=bootstrapCutoffDate&&(!range.from||bootstrapCutoffDate>range.from)?bootstrapCutoffDate:range.from;if(syncFromDate&&range.to&&range.to<syncFromDate)throw new Error('SYNC_TO_DATE must not be before BOOTSTRAP_CUTOFF_DATE'); let symbolOverrides:SymbolOverride[]=[]; if(env.PPI_SYMBOL_OVERRIDES) symbolOverrides=parseSymbolOverrides(JSON.parse(env.PPI_SYMBOL_OVERRIDES)); const cashAssets=env.PPI_CASH_ASSETS?parseCashAssetMap(JSON.parse(env.PPI_CASH_ASSETS)):{}; return {ppi:loadPpiConfig(env),ghostfolio:{url:v.GHOSTFOLIO_URL,accessToken:v.GHOSTFOLIO_ACCESS_TOKEN??'',securityToken:v.GHOSTFOLIO_SECURITY_TOKEN,accountId:v.GHOSTFOLIO_ACCOUNT_ID,batchSize:v.GHOSTFOLIO_BATCH_SIZE},dryRun:v.DRY_RUN==='true',logLevel:v.LOG_LEVEL,syncFromDate,syncToDate:range.to,bootstrapCutoffDate,symbolOverrides,cashAssets}; }
